# Generated by Django 6.0 on 2026-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('delivery', 'Delivery Staff'), ('maintenance', 'Maintenance Staff'), ('admin', 'Admin')], max_length=20),
        ),
    ]
